version: 2

build:
  os: ubuntu-22.04 
  tools:
    python: "3.12" 

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
    - method: pip
      dependencies:
        - sphinx
        - sphinx-rtd-theme
        - myst-parser
    
sphinx:
  configuration: docs/conf.py
  